spring.config.import=classpath:application-local.properties
spring.application.name=Job Portal
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURSE_USERNAME}
spring.datasource.password=${SPRING_DATASOURSE_PASSWORD}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=none